Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,7 +33,14 @@ jobs:
       run: npx playwright install chromium
 
     - name: Run Playwright tests with sharding
-      run: npm run test -- --shard ${{ matrix.shard }}
+      run: npx playwright test --config=playwright.config.js --shard ${{ matrix.shard }}
+
+    - name: Check if report directory exists
+      run: |
+        if [ ! -d "playwright-report" ]; then
+          echo "Report directory not found."
+          exit 1
+        fi
 
     - name: Set shard environment variable for artifact name
       run: echo "SHARD_NAME=shard-${{ matrix.shard }}" | sed 's/\//-/g' >> $GITHUB_ENV
